
DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id_pessoa INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL
);

CREATE TABLE senas(
  id_sena INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nros VARCHAR(100) NOT NULL
);

SELECT * FROM senas ORDER BY id_sena DESC;

INSERT INTO senas(nros) 
VALUES('20 25 30 35 40 45');